# Custom aliases performed on $(date) by fedoraFreshInstall.sh script.
alias ll='ls -lah'
alias rm='rm -vi'
alias cp='cp -vi'
alias mv='mv -vi'
alias dmc='dnf makecache'
alias dup='sudo dnf -y update'
alias dug='sudo dnf -y upgrade'
alias din='sudo dnf -y install'
alias dse='dnf search'
